config/routes.rb
Rails.application.routes.draw do
  resources :campaigns, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'campaigns#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  validates :identifier, presence: true
  has_many :candidates, dependent: :destroy
  has_many :votes, through: :candidates
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name, presence: true
  belongs_to :campaign
  has_many :votes, dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :candidate
  delegate :campaign, to: :candidate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = Campaign.all.filter { |campaign| campaign.votes.count.positive? }
  end

  def show
    @campaign = Campaign.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_helper.rb
module CampaignHelper
end

app/views/campaigns/index.html.erb
<h1>Campaigns</h1>
<table>
  <tr>
    <th>
      Campaign Identifier
    </th>
  </tr>
  <% @campaigns.each do |campaign| %>
    <tr>
      <td>
        <%= link_to campaign.identifier, campaign_path(campaign.id) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/campaigns/show.html.erb
<h1>Campaign: <%= @campaign.identifier %></h1>
<p>Number of valid votes: <%= @campaign.votes.count %></p>
<p>Number of uncounted votes: <%= @campaign.vote_errors %> </p>
<table>
  <tr>
    <th>Candidates<th>
    <th>Score<th>
  </tr>
  <% @campaign.candidates.each do |candidate| %>
    <tr>
      <td><%= candidate.name %><td>
      <td><%= candidate.votes.count %><td>
    </tr>
  <% end %>

</table>
<table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Televote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>